#!/usr/bin/env python3
import os
import csv
import shutil
import re
#this takes an input from calls.txt, generated by gsc_recursive.py
#which in turn takes an input from gsc.txt, generated by a find of gsc files, executing md5sum
#format:
#00b291eb4698e645fc5873b52129a11b        mp_db_crash     _bidon  maps/mp/_bidon

ROOT = "/home/dev/source/final_server_items/finalunzippediwds"
OUT_ROOT = "/home/dev/generated_gsc/"
CALLS = "/home/dev/calls_sorted.txt"

def copy2_no_overwrite(src, dst):
        if os.path.exists(dst):
            return False  # or raise, or log
        shutil.copy2(src, dst)
        return True

def read_calls():

     with open(CALLS, "r") as f:
        for line in f:
            line_split=line.strip().split("\t")
            md5, themap, function, scriptfile = line_split
            source_file_functional = os.path.join(ROOT,themap,scriptfile + ".gsc")
            source_file_toplevel = os.path.join(ROOT, themap, "maps/mp", themap + ".gsc")
            scriptfilesplit = scriptfile.split("/")
            outscriptfile = scriptfilesplit[-1]
            outscriptpath = scriptfilesplit[0:-1]
            spath = "/".join(outscriptpath)
            #for i in range(0,len(outscriptpath)):  #this copies the path
            #    spath += "/" + outscriptpath[i]     #nothing about reading the file
            dest_file_functional = os.path.join(OUT_ROOT,  spath,  outscriptfile + "x" + md5[:6] + ".gsc")
            dest_file_toplevel = os.path.join(OUT_ROOT, "maps","mp",themap + ".gsc")

        #regex
            source_call_regex = r"\\%s(?=\s*::)" % function
            replacement_call_regex = r"\\%sx%s" % (function, md5[:6])

            os.makedirs(os.path.dirname(dest_file_functional), exist_ok=True)
            os.makedirs(os.path.dirname(dest_file_toplevel), exist_ok=True)

            shutil.copy2(source_file_functional,dest_file_functional)
            copy2_no_overwrite(source_file_toplevel,dest_file_toplevel)
            with open(dest_file_toplevel,"r",encoding="cp1252") as f:
                dest_contents = f.read()
                dest_contents = re.sub(source_call_regex,replacement_call_regex,dest_contents,flags=re.MULTILINE|re.IGNORECASE)
            with open (dest_file_toplevel,"w", encoding="cp1252") as f:
                f.write(dest_contents)


            print(f"DFF {dest_file_functional}")
            print(f"DFT {dest_file_toplevel}")
            print(f"SFF {source_file_functional}")
            print(f"SFT {source_file_toplevel}")
            print(f"SCR {source_call_regex}",f"RCR {replacement_call_regex}\n")

if __name__ == "__main__":

    read_calls()
